# Generated by Django 5.2.1 on 2025-05-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubapp', '0002_alter_contact_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('mission', models.TextField(blank=True)),
                ('admin_name', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='clubs/')),
            ],
        ),
    ]
