# Generated by Django 5.2.1 on 2025-05-16 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubapp', '0003_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='past_events',
            field=models.TextField(blank=True, help_text='Add each event on a new line.'),
        ),
        migrations.AddField(
            model_name='club',
            name='resources',
            field=models.TextField(blank=True, help_text='Add each resource on a new line.'),
        ),
        migrations.AlterField(
            model_name='club',
            name='admin_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='club',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='club_images/'),
        ),
        migrations.CreateModel(
            name='ClubGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='club_gallery/')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='clubapp.club')),
            ],
        ),
    ]
