# Generated by Django 5.2.1 on 2025-05-16 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubapp', '0004_club_past_events_club_resources_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubGalleryMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='club_gallery/')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_media', to='clubapp.club')),
            ],
        ),
        migrations.DeleteModel(
            name='ClubGalleryImage',
        ),
    ]
