# Generated by Django 5.2.1 on 2025-05-16 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubapp', '0005_clubgallerymedia_delete_clubgalleryimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='resources',
        ),
        migrations.CreateModel(
            name='ClubResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/')),
                ('link', models.URLField(blank=True, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='clubapp.club')),
            ],
        ),
    ]
