# Generated by Django 5.2.1 on 2025-05-17 18:19

import clubapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubapp', '0007_club_admin_key_club_admin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='admin_key',
            field=models.CharField(default=clubapp.models.generate_unique_admin_key, max_length=35),
        ),
    ]
