# Generated by Django 6.0.4 on 2026-09-25 12:42

import clubapp.models
import clubapp.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubapp', '0013_encrypt_admin_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubgallerymedia',
            name='file',
            field=models.FileField(storage=clubapp.storage.GalleryMediaCloudinaryStorage(), upload_to='club_gallery/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'mp4', 'webm', 'mov']), clubapp.models.validate_media_size]),
        ),
    ]
